# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 17a6b18b8006d390e476d419631aae885cadfa40 # frozen: 0.12.17
    hooks:
      - id: uv-lock

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 5c9b20b95f2bc1c4d3d929b83a96d5c96a29e752 # frozen: v3.9.8
    hooks:
      - id: prettier

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2eeb5678de71a00c0902cbda7105d328432f72cb # frozen: v0.16.8
    hooks:
      # Run the linter.
      - id: ruff-check
        args:
          - --fix
          - --show-fixes
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: ty
        name: ty-check
        language: python
        entry: ty check
        pass_filenames: false
        additional_dependencies:
          - ty==0.0.1a18
          - aiohttp==3.9.3
